### ISSUE TITLE
Constraint on pyjwt<2 is breaking things

### ISSUE THREAD

**Issue by asherf** [duosecurity/duo_universal_python#3]
Hi, 
I am trying to migrate to this package (as part of migrating to the universal prompt - https://duo.com/docs/universal-prompt-update-guide)
However, the constraint on the pyjwt conflicts with another package that we use:https://github.com/python-social-auth/social-core/blob/master/requirements-base.txt#L4
Note that the reason tests are breaking is because pyjwt 2 dropped support for python 2.7 and python 3.5 both are EOL for a while now...
Maybe this library can drop support for those too ?
Alternatively, the  setup.py can be modified to have a different pyjwt for different python version, i.e. python 3.5 & 2.7 have the pyjwt<2 constraint and for newer versions the constraint can be pyjwt>=2

**Comment by AaronAtDuo** [comment]
@asherf Thanks for letting us know about this.  pyJWT 2.0 introduced a change that breaks our client beyond just the Python version issues, so that is the reason for the limitation.  We plan to make the necessary adjustments soon and relax that limitation.

Thanks for using Duo and keep an eye out for the update!
Aaron

**Comment by AaronAtDuo** [comment]
@asherf We've made the changes to use PyJWT 2.0.0+.  CI is broken at the moment for Python 2, but I don't think you'll mind.  We'll do a release shortly!
