### ISSUE TITLE
Example parameter typo

### ISSUE THREAD

**Issue by nickineering** [duosecurity/duo_universal_python#8]
https://duo.com/docs/duoweb#wait-for-the-redirect-from-duo-back-to-your-redirect-uri

You include the following example code at the above url:

```
code = request.args.get('code')
```

That does not work for me, but with `duo_` prefixed to the parameter name it does. I assume it is a typo and it should actually read the following:

```
code = request.args.get('duo_code')
```

**Comment by DuoKristina** [comment]
In the [OAuth API authorization request](https://duo.com/docs/oauthapi#authorization-request) there is an optional argument `use_duo_code_attribute` that when `true` changes the authorization code parameter name from `code` to `duo_code`. Our Duo Web SDKs set this argument to`true` so that `duo_code` is the resultant parameter name.

We've updated the Web SDK document to reflect this.

Thanks again for opening issues to get the Web SDK document corrected.

**Comment by AaronAtDuo** [comment]
@nickineering

Duo is looking to learn how to significantly improve the developer experience and what tools, resources, and technology (eg: sandboxes, new sdks, etc.) would best-enable customers to work faster and build things more easily with Duo's developer ecosystem. If your org is a Duo customer, and you have done development work (ex; authentication integrations, creation of a homegrown admin tool, log consumption for SIEMS, etc) with Duo's developer tools/resources in the past year, we would love to speak with you about your experience, what tools/resources you used, and your pain points.
This will be a 60-minute session during which you’ll have the opportunity to discuss your honest thoughts and feedback with Duo researchers. No preparation is necessary, and please know that this is not a sales call or product demo.
If you’re interested in participating, please email [lli@duosecurity.com](mailto:lli@duosecurity.com) to start the scheduling process.
Once the 60-minute session is complete, you will receive a token of appreciation in the form of a $75 e-gift card through Tremendous (options for Amazon or select retailers).
Please let me know if you have any questions!
Thanks!
